### ISSUE TITLE
User story: Style all pages

### ISSUE THREAD

**Issue by maniacalhamster** [cse110-sp21-group10/cse110-sp21-group10#20]
<?> pts

Pages will be styled to look more like the wireframes

- [ ] Defined by team that takes this task on

**Comment by asya-balas** [comment]
- [ ] Daily Log Styling
   - [ ] Trackers
   - [ ] Related Sections
- [ ] Monthly Log Styling
   - [ ] Calendar 
   - [ ] Notes
   - [ ] Trackers
- [ ] Yearly Log Styling
   - [ ] Calendar
   - [ ] Goals 
   - [ ] Notes
